//Cleanup after ourselves so we don't litter the namespace
#undef TEMPLATE_TYPE
#undef TEMPLATE_INTERNAL_NAME
#undef TEMPLATE_INTERNAL_staticish
#undef TEMPLATE_INTERNAL_externish
#undef TEMPLATE_INTERNAL_CAT
#undef TEMPLATE_INTERNAL_CAT_
#undef TEMPLATE_INTERNAL_CAT__
#undef TEMPLATE_INTERNAL_FullName
#undef TEMPLATE_INTERNAL_PREFIX_CAT
#undef TEMPLATE_INTERNAL_SHORT_CAT
#undef TEMPLATE_INTERNAL_vTable
#undef TEMPLATE_INTERNAL_func_name
#undef TEMPLATE_INTERNAL_TYPE_NAME
