//Cleanup after ourselves so we don't litter the namespace
#undef TEMPLATE_TYPE
#undef TEMPLATE_INTERNAL_NAME
#undef TEMPLATE_INTERNAL_CAT
#undef TEMPLATE_INTERNAL_CAT_
#undef TEMPLATE_INTERNAL_FULL_NAME
#undef TEMPLATE_INTERNAL_PREFIX_CAT
#undef TEMPLATE_INTERNAL_SHORT_CAT
#undef TEMPLATE_INTERNAL_VTABLE
#undef TEMPLATE_INTERNAL_FUNC_NAME
